name: AccuKnox IaC

on:
  push:
    branches:
      - master

jobs:
  iac:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run AccuKnox IaC Scan
        uses: Vickydew1/Accuknox-Code-Analysis@main
        with:
          scan_type: "iac"

          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          accuknox_label: ${{ secrets.ACCUKNOX_LABEL }}

          soft_fail: true
          upload_artifact: true