name: AccuKnox SCA

on:
  push:
    branches:
      - master

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run AccuKnox SCA
        uses: Vickydew1/Accuknox-Code-Analysis@main
        with:
          scan_type: "sca"

          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          accuknox_label: ${{ secrets.ACCUKNOX_LABEL }}

          sca_severity: "HIGH,CRITICAL"

          soft_fail: true
          upload_artifact: true