name: AccuKnox Secret Scan

on:
  push:
    branches:
      - master

jobs:
  secret:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Required for git-based secret scanning

      - name: Run AccuKnox Secret Scan
        uses: Vickydew1/Accuknox-Code-Analysis@main
        with:
          scan_type: "secret"

          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          accuknox_label: ${{ secrets.ACCUKNOX_LABEL }}

          soft_fail: true
          upload_artifact: true