name: TruffleHog Scan

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:

jobs:
  accuknox-secret-scan:
    runs-on: ubuntu-latest
    environment: Stage

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: AccuKnox Secret Scan
        uses: accuknox/secret-scan-action@latest
        with:
          accuknox_token: ${{ secrets.AK_TOK }}
          accuknox_label: "dogfooding"
          accuknox_endpoint: "cspm.stage.accuknox.com"
          sbom_project: "github-test"   # <-- Add here
          soft_fail: true